# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM python:3.10-alpine

WORKDIR /app

# set environment variables
ENV OPENAIKEY


# install the requirements
COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .

EXPOSE 5000/tcp

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
# CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]